### ISSUE TITLE
Iteratively update the example form with every new feature

### ISSUE THREAD

**Issue by sulthan-ahmed** [UKHomeOffice/hof#40]
As part of my Hof Spike/feasibility, our RT/EVW/GE teams agreed it would be helpful if the example up was constantly updated whenever a new feature was added.  I've noticed it hasn't been updated since I last used it from November e.g.
The BRP app has a feature for typeheads.  My team was interested in incorporating so it would be useful to see

**Comment by easternbloc** [comment]
Please raise this in the https://github.com/UKHomeOffice/hof-example-form
