### ISSUE TITLE
Node and npm version

### ISSUE THREAD

**Issue by sulthan-ahmed** [UKHomeOffice/hof#51]
What node version? I couldn't find it in the documentation.  It's been suggested that it should be in package.json

**Comment by daniel-ac-martin** [comment]
In travis we test it on v0.12 upwards.

**Comment by sulthan-ahmed** [comment]
It would be good if it was in the documentation somewhere.  Some guys in the RT team claim it works with node 4.2.2 and npm v2 only

**Comment by daniel-ac-martin** [comment]
Those guys are probably using redis-crypto (nothing to do with hof itself, though it is in brp_app and may be in the example form) which has a bug in recent versions of node.

For example brp_app will currently only run on node 4.2.3 and earlier. (Actually 5.0.0 works too but nothing else on v5.)

**Comment by sulthan-ahmed** [comment]
Actually RT team are just about to implement Hof now.  The problem is our current infrastructure is node 4.2.2 and npm is version 3.  So we are having to work out whether to use docker for it or nvm

**Comment by timgent** [comment]
Not sure why you would need to use nvm for deployment...? Why not just use docker and have your container include the version of node and npm that you need?

**Comment by daniel-ac-martin** [comment]
If it's any help, brp_app's acceptance tests pass with node 5.0.0 and npm 3.3.6 and the hof's master branch.

So I don't think that npm should really be a problem.

**Comment by daniel-ac-martin** [comment]
@easternbloc Tells me he intends to investigate whether there is an npm issue or not.

**Comment by sulthan-ahmed** [comment]
We've tried to run the example app @daniel-ac-martin with npm 3 and it didn't work

**Comment by easternbloc** [comment]
@sulthan-ahmed a stack trace would be appreciated :)

**Comment by sulthan-ahmed** [comment]
thanks @easternbloc the new node version and npm version didn't seem to work for the old example-form but now it's been upgraded.  All seems good :+1:

**Comment by JoeChapman** [comment]
@easternbloc @sulthan-ahmed can this issue be closed?

**Comment by easternbloc** [comment]
:+1:

**Comment by sulthan-ahmed** [comment]
Yes, I'll put in a PR for the documentation.  If anyone has questions around versioning, it'll be there.
