### ISSUE TITLE
Remove i18n-future

### ISSUE THREAD

**Issue by joefitter** [UKHomeOffice/hof#85]
This dependency should be forked or replaced as it is no longer maintained. There is a bug on this line - https://github.com/lennym/i18n-future/blob/master/lib/translator.js#L41- If the handler throws an error its swallowed by process.nextTick so leads some very hard to find bugs. I would prefer to use a more popular maintained version such as https://github.com/mashpie/i18n-node

**Comment by easternbloc** [comment]
> This dependency should be forked or replaced as it is no longer maintained.

There may not be new features being developed (although there's not much need afaik) but the project is not dead. If you raise an issue or a PR you will get feedback from the author.

I don't mind looking at alternatives but I don't think it's fair to warrant it's removal for this.

**Comment by joefitter** [comment]
It makes me very nervous to have such a core part of our architecture built by someone that used to work here, the lib has 4 stars and 2 watchers. If it is just used for HOF I would prefer to use a forked version that we have ownership of and are able to make quick fixes too if needs be. It may be the case that if a PR is submitted it will be addressed, but I don't have much faith in dependencies being kept up to date etc. There is another lib by the same author - https://github.com/lennym/fs-tree-traverse - uses a version of graceful-fs that isn't compatible with node >= v6. Last commit was feb 2015.

I appreciate new features may not be required but I strongly feel that dependencies should be kept updated, and if something is developed purely for use by HOD, such as these libs, then they should be owned by UKHomeOffice github group. Thoughts @JoeChapman @easternbloc @daniel-ac-martin ?

**Comment by daniel-ac-martin** [comment]
My understanding is that Lenny built most of the HMPO form stack. Presumably, he released i18n-future on his own account because it wasn't HMPO specific.

That said, if it isn't being updated we should probably fork or replace it with a competing library.

**Comment by easternbloc** [comment]
@joefitter the dependency argument is a valid one. I just feel it a little harsh that because the project has no commits it's been considered dead. I'm certain that if we were to raise a PR it would be reviewed.

_Scratch that. I've just noticed that Lenny added me as a contributor some time ago. So we can update at our leisure._

**Comment by joefitter** [comment]
Aaah well that's different, unless you leave too... ;)

**Comment by easternbloc** [comment]
@joefitter agreed. I should be able to get other developers added to the repo as needed. I'm going to close this issue for now. Can you please raise an issue for the bug on the i18n repo?
